# nReader v1.1
# Copyright (C) 2025 hediibl
# Licensed under the GNU GPL v3

import os, html
from datetime import datetime

DEFAULT_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/"/>
    <meta charset="UTF-8"/>
    <link rel="icon" type="image/svg" href="favicon.svg"/>
    <link rel='stylesheet' href='default.css'/>
    <title>nReader</title>
    <style></style>
</head>
<body>
    <h1>nReader</h1>
    <p>The collaborative Wii NAND database
        <br/>
        <a href="https://nreader.eu">Home</a> • 
        <a href="https://github.com/hediibl/nReader" target="_blank" rel="noopener noreferrer">Download</a> • 
        <a href="mailto:hedi.jigglypuff@proton.me">Contact</a>
    </p>
    <hr/>
    <section>
        <h2>TBD_SERIAL</h2>
        <p>Generated by <b id='user'>TBD_USER</b> on <b id='date'>TBD_DATE</b>.</p>
        <br/>
        <table>
            <tr><th>ID</th><th>Game ID</th><th>Type</th><th>Name</th><th>Title ?</th><th>Ticket ?</th></tr>
            TBD_ROWS
        </table>
        <hr/>
    </section>
</body>
</html>
"""

LOCAL_CSS = """
<style>
/* ================================
   Global Reset and Base Styles
================================ */
html, body { 
    height: 100%;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    color: white;
    background-color: black;
    font-family: Consolas, Menlo, "Liberation Mono", "DejaVu Sans Mono", system-ui, monospace;
    font-size: 12px;
    padding: 20px;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-start;
    text-align: center;
    overflow-y: auto;
}

/* ================================
   Sections and Horizontal Rules
================================ */
section { 
    text-align: left;
    width: 100%;
    max-width: 1440px;
    margin-bottom: 20px;
}

hr {
    border: 1px solid white; 
    transform: scaleY(0.5);
    width: 100%; 
    max-width: 1440px;
}

/* ================================
   Headings
================================ */
h1, h2 {
    margin: 0; 
}

/* ================================
   Links
================================ */
a { 
    color: cyan;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* ================================
   Tables
================================ */
table {
    border-collapse: collapse;
    width: 100%;
}

th, td { 
    padding: 3px 10px;
    border: 1px solid white;
    word-break: break-word;
}

th {
    background-color: darkslategray;
    color: white;
}

/* ================================
   Status Colors
================================ */
.red { color: red; }
.green { color: lime; }
.gray { color: gray; }

/* ================================
   Responsive adjustments
================================ */
@media (max-width: 768px) {
    body {
        padding: 10px;
        font-size: 11px;
    }

    th, td {
        padding: 2px 5px;
    }
}
</style>
"""

def rotateLeft32(x: int) -> int:
    return ((x << 1) & 0xFFFFFFFF) | (x >> 31)

def xorEncrypt(buf: bytes, isEnc: bool) -> bytes:
    key = 0x73B5DBFA
    data = bytearray(buf)
    length = len(data) if isEnc else min(256, len(data))
    for i in range(length):
        data[i] ^= key & 0xFF
        key = rotateLeft32(key)
    return bytes(data)

def getSerialNumber(settingPath: str) -> str:
    if not os.path.isfile(settingPath):
        raise FileNotFoundError(f"Settings file not found: {settingPath}")
    
    with open(settingPath, "rb") as f:
        encrypted = f.read()
    
    decrypted = xorEncrypt(encrypted, isEnc=True)
    parameters = decrypted.decode("ascii", errors="ignore").split("\r\n")
    
    if len(parameters) < 6:
        raise ValueError("Settings file corrupted or invalid format")
    
    try:
        part1 = parameters[4].split("=")[1]
        part2 = parameters[5].split("=")[1]
    except IndexError:
        raise ValueError("Serial number fields missing in settings")
    
    return f"{part1}{part2}"

def insertColor(status: str) -> str:
    statusMap = {"No": "red", "N/A": "gray"}
    color = statusMap.get(status, "green")
    return f"<span class='{color}'>{html.escape(status)}</span>"

def makeHtmlContent(settingPath: str, uidEntries: dict, userName: str, doShare: bool):
    serialNumber = getSerialNumber(settingPath)
    
    rows = []
    for uid, entry in uidEntries.items():
        rows.append(
            f"<tr>"
            f"<td>{html.escape(str(uid))}</td>"
            f"<td>{html.escape(str(entry.get('gid', '')))}</td>"
            f"<td>{html.escape(str(entry.get('type', '')))}</td>"
            f"<td>{html.escape(str(entry.get('name', '')))}</td>"
            f"<td>{insertColor(entry.get('title', 'N/A'))}</td>"
            f"<td>{insertColor(entry.get('ticket', 'N/A'))}</td>"
            f"</tr>"
        )
    
    htmlContent = DEFAULT_HTML.replace("TBD_SERIAL", html.escape(serialNumber))
    htmlContent = htmlContent.replace("TBD_USER", html.escape(userName))
    htmlContent = htmlContent.replace("TBD_DATE", datetime.now().strftime("%B %d, %Y %H:%M:%S"))
    htmlContent = htmlContent.replace("TBD_ROWS", "\n".join(rows))
    
    if not doShare:
        htmlContent = htmlContent.replace("<style></style>", LOCAL_CSS)
    
    return serialNumber, htmlContent